canonical:
  policies: ["P1","P2","P3","P4","P5","P6","P7","P8","P9","P10"]
  dimensions: ["D1","D2","D3","D4","D5","D6"]
  q_per_dim: 5
overrides:
  # Example: add 2 extra questions to P3-D2
  # P3:
  #   D2: 2
rules:
  default_policy_if_unknown: "P4"
  min_confidence_for_auto_inference: 0.80
