# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: evidence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'evidence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65vidence.proto\x12\x0b\x65vidence.v1\"\xa0\x02\n\x0e\x45videncePacket\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12)\n\x05stage\x18\x02 \x01(\x0e\x32\x1a.evidence.v1.PipelineStage\x12\x18\n\x10source_component\x18\x03 \x01(\t\x12\x15\n\revidence_type\x18\x04 \x01(\t\x12\x14\n\x0c\x63ontent_json\x18\x05 \x01(\t\x12\x12\n\nconfidence\x18\x06 \x01(\x01\x12\x1c\n\x14\x61pplicable_questions\x18\x07 \x03(\t\x12\x15\n\rmetadata_json\x18\x08 \x01(\t\x12\x11\n\ttimestamp\x18\t \x01(\t\x12\x11\n\tsignature\x18\n \x01(\t\x12\x15\n\revidence_hash\x18\x0b \x01(\t\"n\n\x13\x45videncePacketBatch\x12,\n\x07packets\x18\x01 \x03(\x0b\x32\x1b.evidence.v1.EvidencePacket\x12\x10\n\x08\x62\x61tch_id\x18\x02 \x01(\t\x12\x17\n\x0f\x62\x61tch_timestamp\x18\x03 \x01(\t\"|\n\rRegistryEntry\x12\x11\n\tprev_hash\x18\x01 \x01(\t\x12+\n\x06packet\x18\x02 \x01(\x0b\x32\x1b.evidence.v1.EvidencePacket\x12\x12\n\nentry_hash\x18\x03 \x01(\t\x12\x17\n\x0fsequence_number\x18\x04 \x01(\x04*\xb6\x04\n\rPipelineStage\x12\x1e\n\x1aPIPELINE_STAGE_UNSPECIFIED\x10\x00\x12\x1f\n\x1bPIPELINE_STAGE_SANITIZATION\x10\x01\x12\"\n\x1ePIPELINE_STAGE_PLAN_PROCESSING\x10\x02\x12\x1f\n\x1bPIPELINE_STAGE_SEGMENTATION\x10\x03\x12\x1c\n\x18PIPELINE_STAGE_EMBEDDING\x10\x04\x12!\n\x1dPIPELINE_STAGE_RESPONSIBILITY\x10\x05\x12 \n\x1cPIPELINE_STAGE_CONTRADICTION\x10\x06\x12\x1b\n\x17PIPELINE_STAGE_MONETARY\x10\x07\x12\x1e\n\x1aPIPELINE_STAGE_FEASIBILITY\x10\x08\x12\x19\n\x15PIPELINE_STAGE_CAUSAL\x10\t\x12\x19\n\x15PIPELINE_STAGE_TEORIA\x10\n\x12\x16\n\x12PIPELINE_STAGE_DAG\x10\x0b\x12!\n\x1dPIPELINE_STAGE_REGISTRY_BUILD\x10\x0c\x12 \n\x1cPIPELINE_STAGE_DECALOGO_LOAD\x10\r\x12 \n\x1cPIPELINE_STAGE_DECALOGO_EVAL\x10\x0e\x12%\n!PIPELINE_STAGE_QUESTIONNAIRE_EVAL\x10\x0f\x12#\n\x1fPIPELINE_STAGE_ANSWERS_ASSEMBLY\x10\x10\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'evidence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINESTAGE']._serialized_start=561
  _globals['_PIPELINESTAGE']._serialized_end=1127
  _globals['_EVIDENCEPACKET']._serialized_start=32
  _globals['_EVIDENCEPACKET']._serialized_end=320
  _globals['_EVIDENCEPACKETBATCH']._serialized_start=322
  _globals['_EVIDENCEPACKETBATCH']._serialized_end=432
  _globals['_REGISTRYENTRY']._serialized_start=434
  _globals['_REGISTRYENTRY']._serialized_end=558
# @@protoc_insertion_point(module_scope)
